id: 01_hello_world
namespace: zoomcamp

inputs:
  - id: name
    type: STRING
    defaults: Will

concurrency:
  behavior: FAIL
  limit: 2             # limit to 2 concurrent runs. 3rd or more will fail

variables:
  welcome_message: "Hello, {{ inputs.name }}!"
  
tasks:
  - id: hello_message
    type: io.kestra.plugin.core.log.Log           # log welcome msg to console
    message: "{{ render(vars.welcome_message) }}"
  
  - id: generate_output
    type: io.kestra.plugin.core.debug.Return      # return/render output
    format: I was generated during this workflow.

  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep       # sleep for 15 seconds
    duration: PT15S # 15 seconds

  - id: log_output
    type: io.kestra.plugin.core.log.Log           # log rendered generate_output.value to the console
    message: "This is an output: {{ outputs.generate_output.value }}"

  - id: goodbye_message
    type: io.kestra.plugin.core.log.Log           # log name to console
    message: "Goodbye, {{ inputs.name }}!"

pluginDefaults:
  - type: io.kestra.plugin.core.log.Log           # set console log level to ERROR
    values:                                       # instead of default level INFO
      level: ERROR

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    # min hr day month dayOfTheWeek (Reference: https://crontab.cronhub.io/)
    cron: "0 10 * * *"  # 10am
    inputs:
      name: Sarah
    disabled: true      # disable trigger, so it does not keep running in the bkgd
